import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Card, Theme, ThemePanel } from '@radix-ui/themes';
import { AnimatePresence } from 'framer-motion';
import Header from '@/components/headers/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        <Theme accentColor='iris' panelBackground='solid'>
          <div className='max-w-7xl  mx-auto'>
            <header>
              <div className='flex w-full '>
                <Header />
              </div>
            </header>
            <div className='flex w-full flex-col'>
              <div className='mx-4 py-2'>
                <Card>{children}</Card>
              </div>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
