name: Build & Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build & Push Image
        run: |
          docker build -t aforamitrai/portfolio:${{ github.sha }} .
          docker push aforamitrai/portfolio:${{ github.sha }}

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: aforamitdev/infra
          token: ${{ secrets.GH_PAT }}
          path: .

      - name: Update image tag
        run: |
		  ls 
          cd infra/base/app
          kustomize edit set image docker.io/aforamitrai/portfolio=aforamitrai/portfolio:${{ github.sha }}

      - name: Commit & push changes
        run: |
          cd infra
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "deploy: portfolio -> ${{ github.sha }}"
          git push